/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/purple-striped_jellyfish.glb --transform --exportdefault -t -o ./public/Model.tsx 
Files: src/assets/purple-striped_jellyfish.glb [30.68MB] > /Users/willnjl/sites/portolio-docs/public/purple-striped_jellyfish-transformed.glb [10.82MB] (65%)
Author: NestaEric (https://sketchfab.com/Nestaeric)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/purple-striped-jellyfish-81be051e683646d3922b2f6e71eafa11
Title: Purple-Striped Jellyfish
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";
import {
	JELLYFISH_ANIMATION_SEQUENCE,
	JELLYFISH_SWIM_X_AMPLITUDE,
	JELLYFISH_SWIM_Y_AMPLITUDE,
	JELLYFISH_SWIM_Z_AMPLITUDE,
	JELLYFISH_SWIM_X_SPEED,
	JELLYFISH_SWIM_Y_SPEED,
	JELLYFISH_SWIM_Z_SPEED,
	JELLYFISH_ANIMATION_FADE_TIME,
} from "@/constants";

type ActionName =
	| "jellyfish|move_1"
	| "jellyfish|move_2"
	| "jellyfish|move_3"
	| "jellyfish|move_4";

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		Object_442: THREE.SkinnedMesh;
		Object_444: THREE.SkinnedMesh;
		Object_446: THREE.SkinnedMesh;
		_rootJoint: THREE.Bone;
	};
	materials: {
		JF_heart: THREE.MeshStandardMaterial;
		JF_skin_in: THREE.MeshStandardMaterial;
		JF_skin_out: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

import { useFrame } from "@react-three/fiber";

export default function Model(props: JSX.IntrinsicElements["group"]) {
	const group = React.useRef<THREE.Group>();
	const { scene, animations } = useGLTF(
		"/purple-striped_jellyfish-transformed.glb"
	);
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone) as GLTFResult;
	const { actions } = useAnimations(animations, group);

	// Use centralized animation sequence from constants
	const animationSequence = JELLYFISH_ANIMATION_SEQUENCE;

	// Animate gentle swimming
	useFrame(({ clock }) => {
		if (group.current) {
			const t = clock.getElapsedTime();
			group.current.position.x =
				Math.sin(t * JELLYFISH_SWIM_X_SPEED) * JELLYFISH_SWIM_X_AMPLITUDE;
			group.current.position.y =
				Math.sin(t * JELLYFISH_SWIM_Y_SPEED) * JELLYFISH_SWIM_Y_AMPLITUDE;
			group.current.position.z =
				Math.cos(t * JELLYFISH_SWIM_Z_SPEED) * JELLYFISH_SWIM_Z_AMPLITUDE;
		}
	});

	React.useEffect(() => {
		// Ensure correct rendering of transparent materials with gel-like properties
		materials.JF_skin_in.side = THREE.DoubleSide;
		materials.JF_skin_in.roughness = 0.1;
		materials.JF_skin_in.metalness = 0;
		materials.JF_skin_in.transparent = true;
		materials.JF_skin_in.opacity = 0.5;
		(materials.JF_skin_in as any).clearcoat = 1.0;
		(materials.JF_skin_in as any).clearcoatRoughness = 0.1;
		materials.JF_skin_in.needsUpdate = true;

		materials.JF_skin_out.side = THREE.DoubleSide;
		materials.JF_skin_out.roughness = 0.15;
		materials.JF_skin_out.metalness = 0;
		materials.JF_skin_out.transparent = true;
		materials.JF_skin_out.opacity = 0.4;
		(materials.JF_skin_out as any).clearcoat = 0.8;
		(materials.JF_skin_out as any).clearcoatRoughness = 0.2;
		materials.JF_skin_out.needsUpdate = true;

		materials.JF_heart.side = THREE.DoubleSide;
		materials.JF_heart.roughness = 0.2;
		materials.JF_heart.metalness = 0;
		(materials.JF_heart as any).clearcoat = 0.6;
		(materials.JF_heart as any).clearcoatRoughness = 0.3;
		materials.JF_heart.needsUpdate = true;
	}, [materials]);

	React.useEffect(() => {
		let currentIndex = 0;

		const playNextAnimation = () => {
			const prev =
				animationSequence[
					(currentIndex - 1 + animationSequence.length) %
						animationSequence.length
				];
			const curr = animationSequence[currentIndex];

			actions[prev]?.isRunning() &&
				actions[prev].fadeOut(JELLYFISH_ANIMATION_FADE_TIME);

			const action = actions[curr];
			if (action) {
				console.log("now playing animation " + curr);
				action
					.reset()
					.setEffectiveTimeScale(1)
					.setEffectiveWeight(1)
					.fadeIn(JELLYFISH_ANIMATION_FADE_TIME)
					.play();
				const duration = action.getClip().duration;
				setTimeout(() => {
					currentIndex = (currentIndex + 1) % animationSequence.length;
					playNextAnimation();
				}, Math.max(0, (duration - JELLYFISH_ANIMATION_FADE_TIME) * 1000));
			}
		};

		playNextAnimation();

		return () => Object.values(actions).forEach((action) => action?.stop());
	}, [actions, animationSequence]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<primitive object={nodes._rootJoint} />
				<skinnedMesh
					name="Object_442"
					geometry={nodes.Object_442.geometry}
					material={materials.JF_heart}
					skeleton={nodes.Object_442.skeleton}
					rotation={[-Math.PI / 2, 0.497, 0]}
				/>
				<skinnedMesh
					name="Object_444"
					geometry={nodes.Object_444.geometry}
					material={materials.JF_skin_in}
					skeleton={nodes.Object_444.skeleton}
					rotation={[-Math.PI / 2, 0.497, 0]}
				/>
				<skinnedMesh
					name="Object_446"
					geometry={nodes.Object_446.geometry}
					material={materials.JF_skin_out}
					skeleton={nodes.Object_446.skeleton}
					rotation={[-Math.PI / 2, 0.497, 0]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/purple-striped_jellyfish-transformed.glb");
