/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/purple-striped_jellyfish-v1.glb --transform --exportdefault -t -o ./public/Model.tsx 
Files: src/assets/purple-striped_jellyfish-v1.glb [37.19MB] > /Users/willnjl/sites/portolio-docs/public/purple-striped_jellyfish-v1-transformed.glb [10.69MB] (71%)
Author: NestaEric (https://sketchfab.com/Nestaeric)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/purple-striped-jellyfish-81be051e683646d3922b2f6e71eafa11
Title: Purple-Striped Jellyfish
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName =
	| "jellyfish|move_1"
	| "jellyfish|move_2"
	| "jellyfish|move_3"
	| "jellyfish|move_4";

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		Object_442: THREE.SkinnedMesh;
		Object_444: THREE.SkinnedMesh;
		Object_446: THREE.SkinnedMesh;
		_rootJoint: THREE.Bone;
	};
	materials: {
		JF_heart: THREE.MeshStandardMaterial;
		JF_skin_in: THREE.MeshStandardMaterial;
		JF_skin_out: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
	const group = React.useRef<THREE.Group>();
	const { scene, animations } = useGLTF(
		"/purple-striped_jellyfish-v1-transformed.glb"
	);
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone) as GLTFResult;
	const { actions } = useAnimations(animations, group);

	React.useEffect(() => {
		if (actions["jellyfish|move_3"]) {
			actions["jellyfish|move_3"].reset().play();
		}
	}, [actions]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<primitive object={nodes._rootJoint} />
				<skinnedMesh
					name="Object_442"
					geometry={nodes.Object_442.geometry}
					material={materials.JF_heart}
					skeleton={nodes.Object_442.skeleton}
					rotation={[-Math.PI / 2, 0.497, 0]}
				/>
				<skinnedMesh
					name="Object_444"
					geometry={nodes.Object_444.geometry}
					material={materials.JF_skin_in}
					skeleton={nodes.Object_444.skeleton}
					rotation={[-Math.PI / 2, 0.497, 0]}
				/>
				<skinnedMesh
					name="Object_446"
					geometry={nodes.Object_446.geometry}
					material={materials.JF_skin_out}
					skeleton={nodes.Object_446.skeleton}
					rotation={[-Math.PI / 2, 0.497, 0]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/purple-striped_jellyfish-v1-transformed.glb");
