/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/ford/2025_ford_transit_courier_trend_15.gltf --transform 
Files: src/assets/ford/2025_ford_transit_courier_trend_15.gltf [53.4KB] > /Users/willnjl/sites/portolio-docs/2025_ford_transit_courier_trend_15-transformed.glb [1.68MB] (-3055%)
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2025-ford-transit-courier-trend-15-391f0e08a9af4a388a669433c55a7dd9
Title: 2025 Ford Transit Courier Trend 1.5
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2025_ford_transit_courier_trend_15-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.outer_glass_Light_Glass_0.geometry} material={materials.PaletteMaterial001} scale={0} />
      <mesh geometry={nodes.blk_mat_Map_B_Plastic_0.geometry} material={materials.Map_B_Plastic} scale={0} />
      <mesh geometry={nodes.Grill_MAP_B_0.geometry} material={materials.MAP_B} scale={0} />
      <mesh geometry={nodes.Transit_courier_badge_badges_0.geometry} material={materials.badges} scale={0} />
      <mesh geometry={nodes._texture_F_Light_Metal_0.geometry} material={materials.F_Light_Metal} scale={0} />
      <mesh geometry={nodes.crome_sticker_TL_Metal_0.geometry} material={materials.TL_Metal} scale={0} />
      <mesh geometry={nodes.Win_Gls_Glass_0.geometry} material={materials.PaletteMaterial002} scale={0} />
      <mesh geometry={nodes.tyre_grip_ture_2_0.geometry} material={materials.ture_2} scale={0} />
      <mesh geometry={nodes.side_wal_phong18_0.geometry} material={materials.phong18} scale={0} />
      <mesh geometry={nodes.interior_Interior_0.geometry} material={materials.Interior} scale={0} />
      <mesh geometry={nodes.DHL_MAP_A_Plastic_0.geometry} material={materials.MAP_A_Plastic} scale={0} />
      <mesh geometry={nodes.blk_TL_Plastic_0.geometry} material={materials.TL_Plastic} scale={0} />
      <mesh geometry={nodes.int_sticker_glass_surr_0.geometry} material={materials.PaletteMaterial003} scale={0} />
      <mesh geometry={nodes.sticker_Light_Black_0.geometry} material={materials.Light_Black} scale={0} />
      <mesh geometry={nodes.alloy_rim1_0.geometry} material={materials.rim1} scale={0} />
      <mesh geometry={nodes.red_glass_red_glass1_0.geometry} material={materials.PaletteMaterial004} scale={0} />
      <mesh geometry={nodes.Rim_AO_RIM_Met_0.geometry} material={materials.AO_RIM_Met} scale={0} />
      <mesh geometry={nodes.mirror_mirrors_0.geometry} material={materials.mirrors} scale={0} />
      <mesh geometry={nodes.blk_plastick_ganchi_0.geometry} material={materials.ganchi} scale={0} />
      <mesh geometry={nodes['25_TourneoCourier_FrontRear_mudflaps_mud_0'].geometry} material={materials.material} scale={0} />
      <mesh geometry={nodes.key_tex_MAP_A_0.geometry} material={materials.MAP_A} scale={0} />
      <mesh geometry={nodes.Inner_rim_Rim_Black_0.geometry} material={materials.Rim_Black} scale={0} />
      <mesh geometry={nodes.Rare_dhl_Cavity_CarPaint_0.geometry} material={materials.CarPaint} scale={0} />
      <mesh geometry={nodes.UC_shassis_0.geometry} material={materials.shassis} scale={0} />
      <mesh geometry={nodes.Disk_Disk_2_0.geometry} material={materials.Disk_2} scale={0} />
      <mesh geometry={nodes.sticker001_black_0.geometry} material={materials.PaletteMaterial005} scale={0} />
    </group>
  )
}

useGLTF.preload('/2025_ford_transit_courier_trend_15-transformed.glb')
