/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/ford/2025_ford_transit_courier_trend_1.5.glb --transform -t -o ./public/Model.tsx 
Files: src/assets/ford/2025_ford_transit_courier_trend_1.5.glb [13.83MB] > /Users/willnjl/sites/portolio-docs/public/2025_ford_transit_courier_trend_1.5-transformed.glb [1.68MB] (88%)
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2025-ford-transit-courier-trend-15-391f0e08a9af4a388a669433c55a7dd9
Title: 2025 Ford Transit Courier Trend 1.5
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    outer_glass_Light_Glass_0: THREE.Mesh
    blk_mat_Map_B_Plastic_0: THREE.Mesh
    Grill_MAP_B_0: THREE.Mesh
    Transit_courier_badge_badges_0: THREE.Mesh
    _texture_F_Light_Metal_0: THREE.Mesh
    crome_sticker_TL_Metal_0: THREE.Mesh
    Win_Gls_Glass_0: THREE.Mesh
    tyre_grip_ture_2_0: THREE.Mesh
    side_wal_phong18_0: THREE.Mesh
    interior_Interior_0: THREE.Mesh
    DHL_MAP_A_Plastic_0: THREE.Mesh
    blk_TL_Plastic_0: THREE.Mesh
    int_sticker_glass_surr_0: THREE.Mesh
    sticker_Light_Black_0: THREE.Mesh
    alloy_rim1_0: THREE.Mesh
    red_glass_red_glass1_0: THREE.Mesh
    Rim_AO_RIM_Met_0: THREE.Mesh
    mirror_mirrors_0: THREE.Mesh
    blk_plastick_ganchi_0: THREE.Mesh
    ['25_TourneoCourier_FrontRear_mudflaps_mud_0']: THREE.Mesh
    key_tex_MAP_A_0: THREE.Mesh
    Inner_rim_Rim_Black_0: THREE.Mesh
    Rare_dhl_Cavity_CarPaint_0: THREE.Mesh
    UC_shassis_0: THREE.Mesh
    Disk_Disk_2_0: THREE.Mesh
    sticker001_black_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    Map_B_Plastic: THREE.MeshStandardMaterial
    MAP_B: THREE.MeshStandardMaterial
    badges: THREE.MeshStandardMaterial
    F_Light_Metal: THREE.MeshStandardMaterial
    TL_Metal: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    ture_2: THREE.MeshStandardMaterial
    phong18: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    MAP_A_Plastic: THREE.MeshStandardMaterial
    TL_Plastic: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    Light_Black: THREE.MeshStandardMaterial
    rim1: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
    AO_RIM_Met: THREE.MeshStandardMaterial
    mirrors: THREE.MeshStandardMaterial
    ganchi: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    MAP_A: THREE.MeshStandardMaterial
    Rim_Black: THREE.MeshStandardMaterial
    CarPaint: THREE.MeshStandardMaterial
    shassis: THREE.MeshStandardMaterial
    Disk_2: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/2025_ford_transit_courier_trend_1.5-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.outer_glass_Light_Glass_0.geometry} material={materials.PaletteMaterial001} scale={0} />
      <mesh geometry={nodes.blk_mat_Map_B_Plastic_0.geometry} material={materials.Map_B_Plastic} scale={0} />
      <mesh geometry={nodes.Grill_MAP_B_0.geometry} material={materials.MAP_B} scale={0} />
      <mesh geometry={nodes.Transit_courier_badge_badges_0.geometry} material={materials.badges} scale={0} />
      <mesh geometry={nodes._texture_F_Light_Metal_0.geometry} material={materials.F_Light_Metal} scale={0} />
      <mesh geometry={nodes.crome_sticker_TL_Metal_0.geometry} material={materials.TL_Metal} scale={0} />
      <mesh geometry={nodes.Win_Gls_Glass_0.geometry} material={materials.PaletteMaterial002} scale={0} />
      <mesh geometry={nodes.tyre_grip_ture_2_0.geometry} material={materials.ture_2} scale={0} />
      <mesh geometry={nodes.side_wal_phong18_0.geometry} material={materials.phong18} scale={0} />
      <mesh geometry={nodes.interior_Interior_0.geometry} material={materials.Interior} scale={0} />
      <mesh geometry={nodes.DHL_MAP_A_Plastic_0.geometry} material={materials.MAP_A_Plastic} scale={0} />
      <mesh geometry={nodes.blk_TL_Plastic_0.geometry} material={materials.TL_Plastic} scale={0} />
      <mesh geometry={nodes.int_sticker_glass_surr_0.geometry} material={materials.PaletteMaterial003} scale={0} />
      <mesh geometry={nodes.sticker_Light_Black_0.geometry} material={materials.Light_Black} scale={0} />
      <mesh geometry={nodes.alloy_rim1_0.geometry} material={materials.rim1} scale={0} />
      <mesh geometry={nodes.red_glass_red_glass1_0.geometry} material={materials.PaletteMaterial004} scale={0} />
      <mesh geometry={nodes.Rim_AO_RIM_Met_0.geometry} material={materials.AO_RIM_Met} scale={0} />
      <mesh geometry={nodes.mirror_mirrors_0.geometry} material={materials.mirrors} scale={0} />
      <mesh geometry={nodes.blk_plastick_ganchi_0.geometry} material={materials.ganchi} scale={0} />
      <mesh geometry={nodes['25_TourneoCourier_FrontRear_mudflaps_mud_0'].geometry} material={materials.material} scale={0} />
      <mesh geometry={nodes.key_tex_MAP_A_0.geometry} material={materials.MAP_A} scale={0} />
      <mesh geometry={nodes.Inner_rim_Rim_Black_0.geometry} material={materials.Rim_Black} scale={0} />
      <mesh geometry={nodes.Rare_dhl_Cavity_CarPaint_0.geometry} material={materials.CarPaint} scale={0} />
      <mesh geometry={nodes.UC_shassis_0.geometry} material={materials.shassis} scale={0} />
      <mesh geometry={nodes.Disk_Disk_2_0.geometry} material={materials.Disk_2} scale={0} />
      <mesh geometry={nodes.sticker001_black_0.geometry} material={materials.PaletteMaterial005} scale={0} />
    </group>
  )
}

useGLTF.preload('/2025_ford_transit_courier_trend_1.5-transformed.glb')
