import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Layout/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Bacasime+Antique&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body className={"font-sans text-white bg-blue-600 overflow-x-hidden"}>
				<Header />
				{children}
			</body>
		</html>
	);
}
